In [2]:
import numpy as np

In [3]:
# numpy
# 공학, 수학, 대수학을 처리하는 용도로 사용
# 수치계산 벡터 스칼라 매트릭스 텐서

### array


In [4]:
# list = [1,2,4,'a','b']
# string = "hello python"

L = [1,4,5,7]
test_arr = np.array(L) # 리스트와 유사
test_arr

array([1, 4, 5, 7])

In [5]:
test_arr[1] # indexing
test_arr[1:3]

array([4, 5])

In [6]:
type(test_arr)

numpy.ndarray

In [7]:
test_arr.shape # 원소가 4개인 1차원 array => vector

(4,)

In [8]:
L = [1,2,3,'258']  
np.array(L)    # 넘파이 어레이는 모든 원소가 동일한 데이터 타입으로 구성됨 => 연산 속도가 높다

array(['1', '2', '3', '258'], dtype='<U11')

In [9]:
L = [1,2,3, 3.14]
np.array(L)

array([1.  , 2.  , 3.  , 3.14])

In [10]:
L = [[1,2,4,5], [4,5,6,7], [8,7,5,6]]   # matrix(행렬)
np.array(L)

array([[1, 2, 4, 5],
       [4, 5, 6, 7],
       [8, 7, 5, 6]])

In [11]:
np.array(L).shape # 2차원 matrix

(3, 4)

In [12]:
np.array(L).ndim # 몇차원인가?

2

In [13]:
t = [[[1,2,4,5],[4,5,6,7],[8,7,6,5]],[[1,3,5,6],[5,6,7,9],[9,6,1,2]]]
np.array(t)

array([[[1, 2, 4, 5],
        [4, 5, 6, 7],
        [8, 7, 6, 5]],

       [[1, 3, 5, 6],
        [5, 6, 7, 9],
        [9, 6, 1, 2]]])

In [14]:
np.array(t).shape

(2, 3, 4)

> reshape - 원소 개수는 무조건 맞아야 reshape이 된다.

In [15]:
L = [[1,2,4,5], [4,5,6,4]]
test_mat = np.array(L)
test_mat

array([[1, 2, 4, 5],
       [4, 5, 6, 4]])

In [16]:
test_mat.shape

(2, 4)

In [17]:
test_mat.reshape(4,2) # matrix

array([[1, 2],
       [4, 5],
       [4, 5],
       [6, 4]])

In [18]:
test_mat.reshape(8) # vector

array([1, 2, 4, 5, 4, 5, 6, 4])

In [19]:
test_mat.reshape(2,2,2) # tensor

array([[[1, 2],
        [4, 5]],

       [[4, 5],
        [6, 4]]])

> np.array() : array로 형변환, datatype 지정 가능

In [20]:
L = [[1,2,4,5], [4,5,6,4]]
np.array(L, float)

array([[1., 2., 4., 5.],
       [4., 5., 6., 4.]])

In [21]:
L = [[1,2,4,5], [4,5,6,4]]
np.array(L, str)

array([['1', '2', '4', '5'],
       ['4', '5', '6', '4']], dtype='<U1')

> indexing : arr[row, col]

In [22]:
tm = np.array(L)
tm

array([[1, 2, 4, 5],
       [4, 5, 6, 4]])

In [23]:
tm[0,2] == tm[1][0]

True

In [24]:
tm[0,3] = 500
tm

array([[  1,   2,   4, 500],
       [  4,   5,   6,   4]])

In [25]:
sm = np.array([[1,2,3,4,5],[6,7,8,9,10]])
sm

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
sm[1,2]

8

In [27]:
sm[0, 1:3]

array([2, 3])

In [28]:
sm[:, 3]

array([4, 9])

In [29]:
sm[:, 3:]

array([[ 4,  5],
       [ 9, 10]])

In [53]:
sm[:,1::2]

array([[2, 4],
       [7, 9]])

In [32]:
sm[:,[1,3]]

array([[2, 4],
       [7, 9]])

> arange

In [47]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [48]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
list(np.arange(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [50]:
range(1, 10.5, 0.4)  # range는 실수가 안됨.

TypeError: 'float' object cannot be interpreted as an integer

In [51]:
np.arange(1,10.5,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [52]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

#### Operation

In [53]:
tm = np.arange(30).reshape(5,6)
tm

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [56]:
tm.sum()

435

In [64]:
tm.mean()

14.5

In [57]:
tm.sum(axis=0) # column 방향

array([60, 65, 70, 75, 80, 85])

In [67]:
tm.sum(axis=1) # row 방향

array([ 15,  51,  87, 123, 159])

In [68]:
tm.mean(axis=1)

array([ 2.5,  8.5, 14.5, 20.5, 26.5])

In [69]:
tm.min(axis=0)

array([0, 1, 2, 3, 4, 5])

In [59]:
tm.std(axis=0) # 표준편차

array([8.48528137, 8.48528137, 8.48528137, 8.48528137, 8.48528137,
       8.48528137])

In [60]:
tm.std()

8.65544144839919

> element wise operation : 원소간 연산

In [78]:
arr_a = np.arange(6).reshape(2,3)
arr_b = np.arange(6).reshape(2,3)
arr_a

array([[0, 1, 2],
       [3, 4, 5]])

In [79]:
arr_a + arr_b

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [80]:
arr_a * arr_b

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [81]:
arr_a == arr_b

array([[ True,  True,  True],
       [ True,  True,  True]])

> Broadcasting :   
shape이 서로 다른 array 간에 연산을 하는 경우, shape이 작은 array의 shape이 확장된 후 element 간 연산진행

In [82]:
arr_a + 10  # scalar가 2,3 matrix로 확장되어서 element wise 연산을 한다.

array([[10, 11, 12],
       [13, 14, 15]])

In [83]:
arr_a + np.array([1,2,4])

array([[1, 3, 6],
       [4, 6, 9]])

> Boolean indexing :    
boolean array를 index로 하여 True에 해당하는 값만을 추출   
array의 길이와 boolean array의 길이가 같아야 한다.

In [61]:
ta = np.array([1,4,5,6,3,5,6]) # ta에서 5 이상인 값만 출력하시오
ta >= 5

array([False, False,  True,  True, False,  True,  True])

In [62]:
ta[ta>=5]  # ta[True]

array([5, 6, 5, 6])

In [63]:
# 짝수만 출력
ta[ta%2==0]

array([4, 6, 6])

In [64]:
# 1 ~ 100 사이의 정수에서 20보다 크고 30보다 작은 3의 배수를 출력하시오
he = np.arange(1,101)
he = he[20<he]
he = he[he<30]
he[he%3 == 0]

array([21, 24, 27])

In [66]:
he = np.arange(1,101)
he[(20<he) & (he<30) & (he%3==0)]

array([21, 24, 27])

In [67]:
test_arr = np.arange(1,101)
test_arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [103]:
test_arr > 20

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [104]:
test_arr < 30

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [105]:
test_arr%3 ==0

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False])

In [106]:
(test_arr > 20) & (test_arr < 30) & (test_arr%3 ==0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False,  True, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [107]:
test_arr[(test_arr > 20) & (test_arr < 30) & (test_arr%3 ==0)]

array([21, 24, 27])